/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsReleaseNotes = {
  releaseNotesSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
module.exports = sidebarsReleaseNotes;
